###Practical Questions:




##1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

The purpose of NumPy in scientific computing and data analysis is to provide a powerful library for efficient handling of large arrays and matrices, as well as for performing complex mathematical operations on these data structures. NumPy significantly enhances Python's capabilities in numerical operations, making it ideal for tasks in fields like data science, machine learning, physics, and engineering.

Advantages of NumPy:
* Efficient Array Computations:

NumPy provides the ndarray object, a fast and memory-efficient multidimensional array. This data structure is optimized for large datasets and allows efficient storage and manipulation of data.
Operations on ndarray objects are faster than equivalent operations on Python lists because NumPy uses contiguous memory blocks and lower-level optimizations.
* Vectorization:

NumPy allows vectorized operations, which means that operations can be applied to entire arrays (or parts of arrays) at once, without the need for explicit loops. This leads to simpler code and much faster execution times, as vectorized operations leverage low-level optimizations and parallelism.
* Broadcasting:

NumPy's broadcasting mechanism allows operations between arrays of different shapes and sizes, without the need to reshape them manually. This capability is essential for mathematical operations on arrays with different dimensions and helps reduce code complexity.
* Comprehensive Mathematical Functions:

NumPy provides a wide range of mathematical functions, such as trigonometric, statistical, linear algebra, and random number generation functions. This collection of functions makes it easier to perform complex calculations without needing to write custom functions or use additional libraries.
* Memory Efficiency:

NumPy's arrays consume less memory compared to Python lists because they store elements of the same data type in a contiguous memory block. This also improves cache efficiency, leading to faster execution, especially for large datasets.
* Interoperability with Other Libraries:

NumPy is a foundational library in the Python scientific computing stack, and it integrates well with other libraries, such as pandas, scipy, and scikit-learn. These libraries are built on top of NumPy arrays and use its data structures and functions, creating a powerful ecosystem for data analysis and machine learning.
* Array Manipulation and Reshaping:

NumPy makes it easy to reshape, slice, stack, and split arrays, which is essential in scientific computing where data often needs to be transformed before analysis.

How NumPy Enhances Python's Capabilities for Numerical Operations:

Improved Performance: NumPy's optimized C-based implementation means that operations on large datasets are performed much faster compared to pure Python.
Simplicity and Ease of Use: NumPy's syntax for handling large data structures is more concise and easier to read than native Python code with lists and loops.
Specialized Tools for Scientific Computing: Functions like np.linalg (for linear algebra) and np.fft (for Fourier transforms) add specialized capabilities to Python for handling scientific computations.

##2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


Both np.mean() and np.average() functions are used to calculate the average of elements in an array, but they have some key differences in terms of functionality and flexibility.

np.mean()

- Purpose: Calculates the arithmetic mean of an array along a specified axis.
- Syntax: np.mean(array, axis=None, dtype=None, out=None)

Behavior:

Computes the sum of all elements and divides by the total number of elements.

Can be used along a specified axis, such as rows or columns in a multidimensional array.

Does not support weighting of elements.

Use Case: Use np.mean() when you need a straightforward calculation of the mean and do not require weighted averages.

**example**

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(np.mean(arr))  # Output: 3.0

np.average()

- Purpose: Calculates the weighted average of an array, if weights are provided.
- Syntax: np.average(array, axis=None, weights=None, returned=False)

- Behavior:

Supports an additional parameter, weights, which allows you to assign a weight to each element in the array.

If weights is not provided, it behaves the same as np.mean().

If returned=True, it also returns the sum of weights alongside the weighted average.

- Use Case: Use np.average() when you need to calculate a weighted average, i.e., when some elements should contribute more to the average than others.

**example**

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

weights = np.array([1, 2, 3, 4, 5])

print(np.average(arr, weights=weights))  # Output: 3.6667

#When to Use np.mean() vs np.average()

- Use np.mean() when you need a straightforward average calculation without weights. It is simpler and slightly faster for unweighted calculations.

- Use np.average() when you need a weighted mean, where certain values contribute more to the final average. np.average() is more flexible for such scenarios.

##3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

There are several ways to reverse arrays along different axes. Here’s how you can reverse 1D and 2D arrays using slicing and specific functions.

1. Reversing a 1D Array
For a 1D array (or vector), reversing is straightforward with slicing.

Using Slicing ([::-1])

import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)   # Output: [1, 2, 3, 4, 5]

print("Reversed 1D array:", reversed_1d)  # Output: [5, 4, 3, 2, 1]

2. Reversing a 2D Array
For a 2D array (matrix), you can reverse along different axes, either by rows, columns, or both.

Reversing All Elements (Rows and Columns) Using [::-1, ::-1]

This reverses both rows and columns in the array.

**example**

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse all elements
reversed_2d = arr_2d[::-1, ::-1]

print("Original 2D array:\n", arr_2d)

# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

print("Fully reversed 2D array:\n", reversed_2d)

# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]


Reversing Rows Only ([::-1, :])

This reverses the rows, flipping the array vertically.

**example**

# Reverse rows

reversed_rows = arr_2d[::-1, :]

print("Rows reversed 2D array:\n", reversed_rows)

# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]


Reversing Columns Only ([:, ::-1])

This reverses the columns, flipping the array horizontally.

**example**

# Reverse columns

reversed_columns = arr_2d[:, ::-1]

print("Columns reversed 2D array:\n", reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]


3. Using np.flip()

NumPy provides a built-in function np.flip() that can reverse an array along a specified axis.

- np.flip(arr, axis=0): Reverses along the rows (vertical flip).
- np.flip(arr, axis=1): Reverses along the columns (horizontal flip).
- np.flip(arr): Reverses all axes (both rows and columns for a 2D array).

**Example with np.flip()**

# Reverse along rows (axis 0)

reversed_rows_flip = np.flip(arr_2d, axis=0)

print("np.flip() reversed rows:\n", reversed_rows_flip)
# Output:

# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Reverse along columns (axis 1)

reversed_columns_flip = np.flip(arr_2d, axis=1)

print("np.flip() reversed columns:\n", reversed_columns_flip)
# Output:

# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# Fully reverse (both axes)

fully_reversed_flip = np.flip(arr_2d)

print("np.flip() fully reversed array:\n", fully_reversed_flip)

# Output:

# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]






##4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Determining the Data Type in a NumPy Array

To check the data type of elements in a NumPy array, you can simply use the .dtype attribute:

**example**

import numpy as np

# Creating an array

arr = np.array([1, 2, 3])

# Checking the data type

print(arr.dtype)  # Output: int64 (or int32 on some systems)



**You can also explicitly specify the data type when creating an array:**

**example**

arr_float = np.array([1, 2, 3], dtype=np.float32)

print(arr_float.dtype)  # Output: float32


Importance of Data Types in Memory Management and Performance

1. Memory Management:

* Different data types use different amounts of memory. For instance, int32 uses 4 bytes per element, whereas int64 uses 8 bytes. Similarly, float64 (the default for floating-point numbers) uses more memory than float32.
* Choosing an appropriate data type can help reduce memory usage, especially when working with large datasets. For example, if you only need integers in a small range, using int16 or int32 instead of int64 can save significant memory.

**Example:**

large_arr = np.ones(1000000, dtype=np.float64)

print(large_arr.nbytes)  # Memory usage with float64

# Output: 8000000 bytes (8 MB)

optimized_arr = np.ones(1000000, dtype=np.float32)

print(optimized_arr.nbytes)  # Memory usage with float32

# Output: 4000000 bytes (4 MB)


2. Performance:

* Smaller data types often lead to faster computations. For example, operations on int32 arrays are generally faster than those on int64 arrays, as they require less memory bandwidth.
* For applications in data science and machine learning, where large amounts of data are processed, choosing the right data type can lead to significant performance improvements. However, it's also important to ensure that the chosen data type has sufficient precision for the calculations.

**example**

# Arrays with different data types
arr_int32 = np.array([1, 2, 3], dtype=np.int32)

arr_int64 = np.array([1, 2, 3], dtype=np.int64)

# Measure computation time for each (in a larger array context)


3. Precision:

The choice of data type impacts the precision of calculations. For instance, float32 has lower precision than float64, which may result in rounding errors during computations. In scientific computations where precision is critical, float64 or float128 might be preferable despite their higher memory usage.
Integer data types like int8 or uint8 have limited ranges, and if values exceed this range, they will wrap around (or overflow). This could lead to unexpected results, so choosing the correct type is essential to avoid precision issues.

4. Data Compatibility:

Ensuring the correct data type can also help with compatibility, especially when interfacing with other libraries or systems that may require data in specific formats. For example, image processing libraries often use uint8 arrays to represent pixel values, while machine learning frameworks may prefer float32 or float64.













##5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray (short for N-dimensional array) is a powerful data structure for handling large, multi-dimensional arrays and matrices. The ndarray is the core of the NumPy library, and it provides fast, efficient, and flexible ways to store and manipulate data in scientific computing and data analysis.

Key Features of ndarrays

1. Homogeneous Data Type:

* All elements in an ndarray must have the same data type (e.g., int32, float64). This allows NumPy to optimize memory usage and computational efficiency, as it doesn't need to handle multiple data types within the same array.

2. N-Dimensional:

* ndarrays can have any number of dimensions. For example, a 1D array is like a Python list, a 2D array is like a matrix, and a 3D array could represent a stack of matrices (e.g., an image with multiple color channels).

3. Fixed Size:

Once created, the size of an ndarray is fixed, meaning the number of elements cannot change. You can still reshape the array (without changing the total number of elements) or create a new array if needed.

4. Efficient Element-Wise Operations:

NumPy supports element-wise operations, making it easy to perform mathematical operations on each element without using loops. This leads to faster execution times, especially for large datasets.
For example, adding two ndarrays of the same shape will result in an array with each element summed element-wise.

5. Vectorized Operations:

ndarrays are designed for vectorized operations, which means you can perform operations on entire arrays without explicitly writing loops. This leverages low-level optimizations and speeds up computation.

**For example:**

import numpy as np

arr = np.array([1, 2, 3])

arr_squared = arr ** 2  # [1, 4, 9]


6. Broadcasting:

NumPy's broadcasting mechanism allows operations on arrays of different shapes without the need to explicitly resize them. For example, adding a scalar to an array automatically adds the scalar to each element of the array, regardless of its shape.

7. Memory Efficiency:

ndarrays are more memory-efficient than Python lists. They store data in contiguous memory locations and use a fixed data type, reducing memory overhead and enabling fast access to elements.

8. Slicing and Indexing:

ndarrays support advanced slicing and indexing techniques, including boolean indexing, fancy indexing, and multidimensional slicing. This provides more control and flexibility when accessing or modifying data.

**How ndarrays Differ from Standard Python Lists**

1. Data Type:

* In a Python list, elements can be of different types (e.g., integers, floats, strings). In contrast, all elements in an ndarray must be of the same data type, which allows for efficient memory usage and faster computations.

2. Memory Usage:

ndarrays are stored in contiguous memory blocks and have lower memory overhead than lists. This is especially beneficial when working with large datasets, as it reduces the memory footprint.

3. Performance:

ndarrays are much faster than Python lists for numerical operations due to their contiguous memory storage, fixed data type, and ability to perform vectorized operations. In scientific computing, where speed is essential, ndarrays provide a significant advantage over lists.

4. Array Operations:

NumPy allows element-wise operations on ndarrays, which isn't possible with lists without using loops. For instance, you can multiply an ndarray by a scalar or add two ndarrays directly, while with lists, you would need to use a loop or list comprehension.

**example**

arr = np.array([1, 2, 3])

arr = arr + 10   # Output: [11, 12, 13]

# With a list:

my_list = [1, 2, 3]

my_list = [x + 10 for x in my_list]  # Output: [11, 12, 13]

5. Multidimensional Arrays:

* While Python lists can store nested lists to create a form of 2D or 3D structures, they are not truly multidimensional and require nested loops to work with. ndarrays, however, are explicitly designed for multiple dimensions, with methods to reshape, slice, and operate across dimensions easily.

6. Built-In Functions:

* NumPy provides numerous built-in functions for operations on ndarrays, such as statistical functions (np.mean, np.sum), mathematical functions (np.sin, np.log), and linear algebra functions (np.dot, np.linalg.inv). Using these functions with lists is often more complex or inefficient, requiring conversion or manual implementations.

**Example Comparison: List vs. ndarray**

import numpy as np

# Using Python lists

my_list = [1, 2, 3, 4]

squared_list = [x ** 2 for x in my_list]

print("Squared List:", squared_list)  # Output: [1, 4, 9, 16]

# Using NumPy ndarray

arr = np.array([1, 2, 3, 4])

squared_array = arr ** 2

print("Squared Array:", squared_array)  # Output: [1 4 9 16]



























##6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


NumPy arrays (ndarrays) offer substantial performance benefits over Python lists, especially for large-scale numerical operations. Here's a breakdown of the advantages and why they make NumPy arrays faster and more efficient:

1. Memory Efficiency
* Contiguous Memory Storage: NumPy arrays are stored in contiguous memory blocks, which enables quick access to elements and efficient use of the CPU cache. This is in contrast to Python lists, which store references to objects in various locations in memory.
* Fixed Data Type: All elements in a NumPy array must have the same data type. This makes it possible for NumPy to store data in a compact form, reducing memory usage. In Python lists, each element is a separate object, which adds memory overhead for large lists.
* Smaller Memory Footprint: For large data, a NumPy array typically takes up significantly less memory than a list, which helps prevent memory overflow and enables the handling of large datasets more easily.

2. Vectorized Operations
* Avoiding Loops: NumPy allows you to perform mathematical operations on arrays without the need for explicit loops. For example, you can add, multiply, or apply mathematical functions across an entire array in a single line, which is highly optimized in C under the hood.
* Parallelization: Many NumPy operations are implemented in low-level languages like C and Fortran, and they take advantage of SIMD (Single Instruction, Multiple Data) processing, where the same operation is applied to multiple elements simultaneously. This leads to significant performance gains.

**example**

import numpy as np

arr = np.array([1, 2, 3, 4])

result = arr * 2  # Multiplies each element by 2


3. Broadcasting
* Automatic Shape Adjustment: NumPy's broadcasting allows operations on arrays of different shapes without explicit resizing, which reduces the need for intermediate memory allocation and makes code more concise and faster.
* Optimized Memory Usage: Broadcasting also minimizes the creation of new arrays and speeds up operations by not duplicating data. In contrast, with lists, you'd have to manually adjust shapes or use loops, which adds overhead.
4. Advanced Indexing and Slicing
* Efficient Subsetting: NumPy provides advanced indexing and slicing techniques, allowing you to quickly access and manipulate subsets of an array without copying the data. This "view" on data avoids unnecessary memory duplication and enables efficient in-place modifications.
* Faster Data Access: Because of contiguous memory storage, accessing a range of elements in a NumPy array is faster than in a list, where each element requires a separate lookup.


5. Built-In Mathematical Functions
* Optimized Algorithms: NumPy has a comprehensive library of mathematical functions (like np.sum, np.mean, np.dot, etc.) that are implemented in compiled code, making them much faster than equivalent operations done manually in Python.
* Batch Processing: These functions allow for "batch processing" of data, applying the function to all elements of the array at once, which is much faster than iterating through each element as you would in a list.

**example**

arr = np.random.rand(1000000)

sum_arr = np.sum(arr)  # Optimized and faster than sum() on a Python list


6. Support for Multidimensional Data
* Efficient Handling of Matrices and Higher-Dimensional Arrays: NumPy is designed for n-dimensional data, allowing efficient storage and manipulation of matrices and tensors. Python lists don't natively support multidimensional structures, and creating them involves nested lists, which adds complexity and inefficiency.
* Matrix Operations: NumPy allows you to perform operations like matrix multiplication, transposition, and other linear algebra functions efficiently. With lists, you'd need to implement these operations manually, which is both time-consuming and computationally expensive.
7. Reduced Function Call Overhead
* Direct Element Manipulation: In NumPy, operations are performed at the C level, bypassing Python's interpreter and reducing function call overhead. Lists require Python-level operations for each element, which adds processing time.


**Example with Lists:** To add two lists element-wise, you'd need a loop or a comprehension:

list1 = [1, 2, 3]

list2 = [4, 5, 6]

result = [x + y for x, y in zip(list1, list2)]


**Performance Comparison Example**

Here's a small code example that demonstrates the difference in performance between a Python list and a NumPy array for element-wise addition:

import numpy as np

import time

# Using Python lists
size = 1000000

list1 = range(size)

list2 = range(size)

start_time = time.time()

result = [x + y for x, y in zip(list1, list2)]

print("Time taken using Python lists:", time.time() - start_time)

# Using NumPy arrays
arr1 = np.arange(size)

arr2 = np.arange(size)

start_time = time.time()

result = arr1 + arr2

print("Time taken using NumPy arrays:", time.time() - start_time)
















##7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.


The vstack() and hstack() functions in NumPy are used to stack arrays vertically and horizontally, respectively. These functions are useful for combining multiple arrays along different axes.

**vstack() (Vertical Stack)**

* vstack() stacks arrays vertically, which means it combines them along rows.
* It requires that the arrays being stacked have the same number of columns.
* The result is a new array with rows from each input array stacked on top of each other.

**Example of vstack() Usage**

import numpy as np

# Define two 1D arrays

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

# Stack them vertically

result = np.vstack((array1, array2))

print("Vertical Stack (vstack) Result:")

print(result)


**Output:**

Vertical Stack (vstack) Result:

[[1 2 3]

 [4 5 6]]


**Explanation**
* array1 and array2 are combined as rows, resulting in a 2x3 matrix.

**hstack() (Horizontal Stack)**
* hstack() stacks arrays horizontally, which means it combines them along columns.
* It requires that the arrays being stacked have the same number of rows.
* The result is a new array with columns from each input array placed side by side.

**Example of hstack() Usage**

# Define two 2D arrays

array1 = np.array([[1], [2], [3]])

array2 = np.array([[4], [5], [6]])

# Stack them horizontally

result = np.hstack((array1, array2))

print("Horizontal Stack (hstack) Result:")

print(result)


**Output:**

Horizontal Stack (hstack) Result:

[[1 4]

 [2 5]

 [3 6]]


**2D Example Comparing vstack() and hstack()**

For a more detailed comparison, let's stack two 2D arrays:

array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

# Vertical stack

vstack_result = np.vstack((array1, array2))

print("Vertical Stack Result:\n",
vstack_result)


# Horizontal stack

hstack_result = np.hstack((array1, array2))

print("\nHorizontal Stack Result:\n", hstack_result)

**Output:**

Vertical Stack Result:

 [[1 2]

  [3 4]

  [5 6]

  [7 8]]

Horizontal Stack Result:

 [[1 2 5 6]

  [3 4 7 8]]












##8. Explain the differences between flipr() and flipud() methods in NumPy, including their effects on various array dimensions.

The flip() function is used to reverse the order of elements along a specified axis. The fliplr() and flipud() functions are special cases of flip() that reverse the order along specific axes for 2D arrays (and higher dimensions). Let's break down each of these functions and see how they work with different array dimensions.


1. fliplr() - Flip Left to Right
fliplr() flips a 2D array (or higher dimensions) horizontally, meaning it reverses the order of columns.
It only affects the second axis (axis 1) of the array, so the rows remain in their original order, but the elements within each row are reversed.
This function requires the array to have at least 2 dimensions; otherwise, it raises an error.

**Example of fliplr()**

import numpy as np

# Create a 2D array

array = np.array([[1, 2, 3],

                  [4, 5, 6],

                  [7, 8, 9]])

# Flip the array horizontally (left to right)

fliplr_result = np.fliplr(array)

print("Original Array:\n", array)

print("Fliplr Result:\n", fliplr_result)




**Output:**


Original Array:
[[1 2 3]
[4 5 6]
[7 8 9]]

Fliplr Result:
[[3 2 1]
[6 5 4][9 8 7]]



2. **flipud() - Flip Up to Down**

* flipud() flips a 2D array (or higher dimensions) vertically, meaning it reverses the order of rows.
* It only affects the first axis (axis 0) of the array, so the columns remain in their original order, but the rows are reversed.
* Similar to fliplr(), it requires the array to have at least 2 dimensions.

**Example of flipud()**

# Flip the array vertically (up to down)

flipud_result = np.flipud(array)

print("Flipud Result:\n", flipud_result)

**Output:**

Flipud Result:

 [[7 8 9]

  [4 5 6]

  [1 2 3]]


Example with a 3D Array
For higher-dimensional arrays, fliplr() and flipud() operate only on the 2D slices of the array.

# Create a 3D array

array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],

                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]]])

# Apply fliplr and flipud to the 3D array

fliplr_result_3d = np.fliplr(array_3d)

flipud_result_3d = np.flipud(array_3d)

print("Original 3D Array:\n", array_3d)

print("\nFliplr on 3D Array:\n", fliplr_result_3d)

print("\nFlipud on 3D Array:\n", flipud_result_3d)

**Output:**

Original 3D Array:

 [[[ 1  2  3]

   [ 4  5  6]

   [ 7  8  9]]

  [[10 11 12]

   [13 14 15]

   [16 17 18]]]

Fliplr on 3D Array:

 [[[ 3  2  1]

   [ 6  5  4]

   [ 9  8  7]]

  [[12 11 10]

   [15 14 13]

   [18 17 16]]]

Flipud on 3D Array:

 [[[10 11 12]

   [13 14 15]

   [16 17 18]]

  [[ 1  2  3]

   [ 4  5  6]

   [ 7  8  9]]]






##9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


The array_split() function in NumPy divides an array into a specified number of sub-arrays. It's particularly useful for splitting data when working with large datasets or performing parallel processing.

**Key Characteristics of array_split()**

1. Flexible Number of Splits: You specify the number of splits, and it divides the array accordingly.
2. Handles Uneven Splits: Unlike split(), which requires the array to be evenly divisible by the number of splits, array_split() allows for uneven splits, distributing extra elements to the beginning sub-arrays.
3. Returns a List of Sub-arrays: Each split section is returned as a new sub-array within a list.

**Syntax**

np.array_split(array, num_splits, axis=0)

* array: The input array you want to split.
* num_splits: The number of parts to split the array into.
* axis: The axis along which the split is performed (default is 0).

**How array_split() Handles Uneven Splits**

If the array length is not perfectly divisible by the number of splits, array_split() will distribute the remainder elements among the initial sub-arrays. This ensures that all parts are as equal in size as possible, with the first sub-arrays being slightly larger if the array size isn't evenly divisible.

**Example of an Even Split**

If the array has 6 elements and you split it into 3 parts, each sub-array will have exactly 2 elements.

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

result = np.array_split(array, 3)

print(result)

**Output**

[array([1, 2]), array([3, 4]), array([5, 6])]

**Example of an Uneven Split**

If the array has 7 elements and you split it into 3 parts, the first two parts will have 3 elements, while the last part will have 1 element.


array = np.array([1, 2, 3, 4, 5, 6, 7])

result = np.array_split(array, 3)

print(result)


**Output**

[array([1, 2, 3]), array([4, 5, 6]), array([7])]


**Splitting Along Other Axes**

You can split multi-dimensional arrays along different axes. For instance, for a 2D array, you can split along axis 0 (rows) or axis 1 (columns).


# 2D array example

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

# Split into 3 parts along columns (axis 1)

result = np.array_split(array_2d, 3, axis=1)

print(result)

**Output:**

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),

 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
         
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]



##10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization and broadcasting are two key concepts in NumPy that enable efficient and fast computations, particularly with large datasets, by leveraging array operations and avoiding explicit loops in Python.

1. **Vectorization**

Definition: Vectorization is the process of applying operations to entire arrays or large blocks of data simultaneously, rather than element by element, by using optimized low-level implementations in NumPy. This approach replaces explicit Python loops with efficient array-level operations.

**Benefits:**

* Performance: Vectorized operations run much faster because they're executed by optimized C and Fortran libraries under the hood.

* Readability: Code becomes cleaner and easier to understand, as operations are performed directly on arrays without explicit loops.

**Example of Vectorization**

Let's say we want to add two lists of numbers element by element.

Without vectorization, we might use a loop:

# Without vectorization

list1 = [1, 2, 3]

list2 = [4, 5, 6]

result = [x + y for x, y in zip(list1, list2)]

print(result)  # Output: [5, 7, 9]

**With vectorization in NumPy:**

import numpy as np

# Using vectorized addition in NumPy

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

result = array1 + array2

print(result)  # Output: [5, 7, 9]


2. **Broadcasting**

Definition: Broadcasting allows NumPy to perform operations on arrays of different shapes by “stretching” the smaller array along the dimension of the larger one without actually copying the data. This process is memory-efficient and enables element-wise operations on arrays of different sizes.

**Broadcasting Rules:**

* If the arrays do not have the same number of dimensions, prepend ones to the smaller array's shape until they match.
* Arrays are compatible for broadcasting if, for each dimension, they are either equal or one of them is 1.
* The output shape will be the maximum size along each dimension of the input arrays.

**Example of Broadcasting**

Consider adding a 1D array to each row of a 2D array:

# 2D array

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# 1D array

array_1d = np.array([10, 20, 30])

# Broadcasting adds array_1d to each row of array_2d

result = array_2d + array_1d

print(result)


Output:

[[11 22 33]

 [14 25 36]

 [17 28 39]]

 **Efficiency in Array Operations**
* Vectorization removes the need for explicit loops, resulting in faster execution and more concise code.
* Broadcasting avoids data duplication by logically expanding arrays, optimizing both memory and computation.

###Practical Questions:


##1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100

array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Step 2: Transpose the array (interchange rows and columns)

transposed_array = array_3x3.T

print("Original 3x3 Array:")

print(array_3x3)

print("\nTransposed Array (Rows and
Columns Interchanged):")

print(transposed_array)


##2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements

array_1d = np.arange(1, 11)  # Creates an array from 1 to 10

# Step 2: Reshape it into a 2x5 array

array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape it into a 5x2 array

array_5x2 = array_1d.reshape(5, 2)

print("1D Array with 10 elements:")

print(array_1d)

print("\n2x5 Array:")

print(array_2x5)

print("\n5x2 Array:")

print(array_5x2)


##3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

# Step 1: Create a 4x4 array with random float values

array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around the 4x4 array to make it 6x6

array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array with Random Float Values:")

print(array_4x4)

print("\n6x6 Array with a Border of Zeros:")

print(array_6x6)


##4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Creating an array of integers from 10 to 60 with a step of 5

array_step = np.arange(10, 61, 5)

print(array_step)


**This code will output an array: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60].**


##5. Create a NumPy array of strings "python", "numpy", "pandas". Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


import numpy as np

# Creating a NumPy array of strings

array_strings = np.array(["python", "numpy", "pandas"])

# Applying different case transformations

uppercase_array = np.char.upper(array_strings)

lowercase_array = np.char.lower(array_strings)

titlecase_array = np.char.title(array_strings)

print("Uppercase:", uppercase_array)

print("Lowercase:", lowercase_array)

print("Title Case:", titlecase_array)


**Output:**

Uppercase: ['PYTHON', 'NUMPY', 'PANDAS']

Lowercase: ['python', 'numpy', 'pandas']

Title Case: ['Python', 'Numpy', 'Pandas']

##6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Creating a NumPy array of words

words_array = np.array(["hello", "world", "numpy", "python"])

# Inserting a space between each character of every word in the array

spaced_words_array = np.char.join(" ", words_array)

print(spaced_words_array)

**Output:**

['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


##7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Creating two 2D NumPy arrays

array1 = np.array([[1, 2, 3], [4, 5, 6]])

array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Performing element-wise operations

addition_result = np.add(array1, array2)

subtraction_result = np.subtract(array1, array2)

multiplication_result = np.multiply(array1, array2)

division_result = np.divide(array1, array2)

print("Addition Result:\n", addition_result)

print("Subtraction Result:\n", subtraction_result)

print("Multiplication Result:\n", multiplication_result)

print("Division Result:\n", division_result)


##8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Creating a 5x5 identity matrix

identity_matrix = np.eye(5)

# Extracting the diagonal elements

diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)

print("Diagonal Elements:", diagonal_elements)


##9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


import numpy as np

# Generate an array of 100 random integers between 0 and 1000

random_array = np.random.randint(0, 1000, 100)

# Helper function to check if a number is prime

def is_prime(n):

  if n < 2:
     return False
  for i in range(2, int(n**0.5) + 1):
     if n % i == 0:
       return False
  return True

# Use vectorized approach to find primes in the array

prime_numbers = np.array([num for num in random_array if is_prime(num)])

print("Random Array:", random_array)

print("Prime Numbers:", prime_numbers)



##10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.


import numpy as np

# Generate an array of 28 daily temperatures for 4 complete weeks

daily_temperatures = np.random.uniform(15, 35, 28)

# Reshape and calculate weekly averages

weekly_temperatures = daily_temperatures.reshape(4, 7)

weekly_averages = weekly_temperatures.mean(axis=1)

print("Daily Temperatures:", daily_temperatures)

print("Weekly Averages:", weekly_averages)
